--CRISTOBAL GUZMAN LORCA
--MDY2131-007V

--REQUERIMIENTO 1
SELECT
    TO_CHAR(C.NUMRUN,'99G999G999')||'-'||C.DVRUN AS "RUT CLIENTE"
    ,PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO AS "NOMBRE CLIENTE"
    ,PO.NOMBRE_PROF_OFIC AS "PROFESION U OFICIO"
    ,TC.NOMBRE_TIPO_CONTRATO AS "TIPO CONTRATO"
    ,TO_CHAR(MAX(PIC.MONTO_TOTAL_AHORRADO),'$999G999G999') AS "MONTO TOTAL AHORRADO"
    ,CASE
        WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 100000 AND 1000000 THEN 'BRONCE'
        WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 1000001 AND 4000000 THEN 'PLATA'
        WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 4000001 AND 8000000 THEN 'SILVER'
        WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) BETWEEN 8000001 AND 15000000 THEN 'GOLD'
        WHEN SUM(PIC.MONTO_TOTAL_AHORRADO) > 15000001 THEN 'PLATINUM'
    END AS "CATEGORIA CLIENTE"
FROM CLIENTE C
        JOIN PROFESION_OFICIO PO ON PO.COD_PROF_OFIC = C.COD_PROF_OFIC
        JOIN TIPO_CONTRATO TC ON TC.COD_TIPO_CONTRATO = C.COD_TIPO_CONTRATO
        JOIN PRODUCTO_INVERSION_CLIENTE PIC ON PIC.NRO_CLIENTE = C.NRO_CLIENTE
GROUP BY C.NUMRUN,C.DVRUN,PNOMBRE,SNOMBRE,APPATERNO,APMATERNO,PO.NOMBRE_PROF_OFIC,TC.NOMBRE_TIPO_CONTRATO
ORDER BY C.APPATERNO, "MONTO TOTAL AHORRADO" DESC
;

--REQUERIMIENTO 2
SELECT 
    TO_CHAR(CC.FECHA_OTORGA_CRED, 'mmYYYY') AS "MES TRANSACCION",
    C.NOMBRE_CREDITO AS "TIPO CREDITO",
    SUM(CC.MONTO_CREDITO) AS "MONTO SOLICITADO CREDITO",
    SUM(CC.MONTO_CREDITO*(ASB.PORC_ENTREGA_SBIF/100)) AS "APORTE A LA SBIF"
FROM MDY2131_P11_1.CREDITO_CLIENTE CC
        JOIN MDY2131_P11_1.CREDITO C ON C.COD_CREDITO = CC.COD_CREDITO
        JOIN MDY2131_P11_1.APORTE_A_SBIF ASB ON CC.MONTO_CREDITO BETWEEN ASB.MONTO_CREDITO_DESDE AND ASB.MONTO_CREDITO_HASTA
WHERE EXTRACT(YEAR FROM CC.FECHA_OTORGA_CRED) = EXTRACT(YEAR FROM SYSDATE)-1
GROUP BY TO_CHAR(CC.FECHA_OTORGA_CRED, 'mmYYYY'), C.NOMBRE_CREDITO
ORDER BY  "MES TRANSACCION" ASC,"TIPO CREDITO"
;
