--GUIA P12
--CRISTOBAL GUZMAN LORCA

--PRIVILEGIOS PARA CREAR CONEXION
GRANT CREATE SESSION TO MDY2131_P12_1;
GRANT "RESOURCE" TO MDY2131_P12_1;
ALTER USER MDY2131_P12_1 DEFAULT ROLE "RESOURCE";
GRANT CREATE VIEW TO MDY2131_P12_1;

--REQUERIMIENTO 2
SELECT 
    TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUN CLIENTE"
    ,INITCAP(C.PNOMBRE)||' '||INITCAP(C.SNOMBRE)||' '||INITCAP(C.APPATERNO)||' '||INITCAP(C.APMATERNO) AS "NOMBRE CLIENTE"
    ,TO_CHAR(C.FECHA_NACIMIENTO,'DD')||' de '||TO_CHAR(C.FECHA_NACIMIENTO,'month') AS "FECHA NACIMIENTO"
    ,C.DIRECCION||', '||UPPER(CO.NOMBRE_COMUNA) AS "DIRECCION"
FROM CLIENTE C
JOIN COMUNA CO ON CO.COD_REGION = C.COD_REGION
                        AND CO.COD_PROVINCIA = C.COD_PROVINCIA
                        AND CO.COD_COMUNA = C.COD_COMUNA
WHERE EXTRACT(MONTH FROM C.FECHA_NACIMIENTO) = (EXTRACT(MONTH FROM SYSDATE))+1
ORDER BY "FECHA NACIMIENTO" ASC, C.APPATERNO
;

--REQUERIMIENTO 3
SELECT
    TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUN CLIENTE"
    ,INITCAP(C.PNOMBRE)||' '||INITCAP(C.SNOMBRE)||' '||INITCAP(C.APPATERNO)||' '||INITCAP(C.APMATERNO) AS "NOMBRE CLIENTE"
    ,PI.NOMBRE_PROD_INV AS PRODUCTO
    ,PIC.FECHA_SOLIC_PROD AS "FECHA SOLICITUD"
FROM CLIENTE C
    JOIN PRODUCTO_INVERSION_CLIENTE PIC ON PIC.NRO_CLIENTE = C.NRO_CLIENTE
    JOIN PRODUCTO_INVERSION PI ON PI.COD_PROD_INV = PIC.COD_PROD_INV
WHERE EXTRACT(YEAR FROM PIC.FECHA_SOLIC_PROD) = (EXTRACT(YEAR FROM SYSDATE))-1
ORDER BY "FECHA SOLICITUD"
;
